apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vnfpb0r2l-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:aa7099ce24ab75c58d290c6bf32d2bce1a4612f0@sha256:1ad4dad1414cfe4d490f9a57828dc9e89e5f835378f325bcb537bc74755be846
          name: container-image
