apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vnfpb0r2l-java-springboot
  janus-idp.io/tekton: vnfpb0r2l-java-springboot
  backstage.io/kubernetes-id: vnfpb0r2l-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vnfpb0r2l-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
